-- ═══════════════════════════════════════════════════════════════
-- Paywall v2 validation (caps + founder code) — run in the Supabase SQL Editor.
-- NOTHING PERSISTS.
--
-- GENERATED by scripts/build-paywall-validation.mjs from:
--   supabase/migrations/20261001000001_paywall_v2_invoice_cap.sql
--   supabase/migrations/20261001000002_paywall_v2_expense_cap.sql
--   supabase/migrations/20261001000003_founder_code.sql
--   supabase/rollbacks/paywall_v2_rollback.sql (applied after the cap tests)
-- Regenerate after changing any of them.
--
-- How it stays safe: this whole file is ONE DO statement. It applies the
-- migrations, tests them against throwaway users (random ids, emails
-- @example.invalid — never a real account), and then deliberately raises an
-- error. A statement that errors is rolled back completely, so the migrations,
-- the users and every test row disappear, however the editor runs it.
--
-- Expected output: an ERROR whose message starts "PAYWALL VALIDATION" and
-- lists one PASS/FAIL line per test. That error is the report, not a problem.
-- It briefly takes the same table locks as the real push; run it at a quiet
-- moment.
-- ═══════════════════════════════════════════════════════════════

do $validate$
declare
  free_u    uuid := gen_random_uuid();
  founder_u uuid := gen_random_uuid();
  report    text[] := '{}';
  passed    int := 0;
  failed    int := 0;
  code_u1   uuid := gen_random_uuid();
  code_u2   uuid := gen_random_uuid();
  code_u3   uuid := gen_random_uuid();
  v_hint    text;
  v_id      uuid;
  v_ts      timestamptz;
  v_status  text;
  v_text    text;
  v_tier    text;
  v_count   int;
  v_rows    int;
begin
  -- ── The migrations, exactly as they will be pushed ─────────
  execute $mig1$
-- ═══════════════════════════════════════════════════════════════
-- Paywall v2, part 1: free invoice cap back on (3), counted from the reset.
--
-- PUSH ON LAUNCH DAY ONLY. Preview and production share this database and the
-- trigger doesn't know about NEXT_PUBLIC_PAYWALL_ENABLED: the cap is live for
-- every user the moment this is pushed.
--
--   1. paywall_reset_at() — a constant equal to the moment THIS migration runs
--      (the transaction's now(), written into the function body). Only rows
--      created at/after it count, so every free user starts at 0. No
--      grandfathering, nothing deleted: older rows stay and just don't count.
--   2. free_invoice_limit() → 3 (was the kill-switch value 1,000,000 from
--      20260823120000, which is left untouched).
--   3. enforce_free_invoice_limit(): counts kind='invoice' rows created since
--      the reset (soft-deleted ones included: deleting refunds nothing).
--      Unlimited: founder / trialing / active / past_due. Capped: free,
--      canceled, null, legacy.
--   4. created_at is server-owned on invoices: the cap trigger stamps now() on
--      insert, and pin_created_at() keeps it unchanged on update. Clients hold
--      INSERT/UPDATE on created_at, so without this a row could be backdated
--      before the reset and never count. Existing rows are not modified.
--
-- The tier rules must match src/lib/access.ts exactly.
-- Rollback (cap → 1,000,000): supabase/rollbacks/paywall_v2_rollback.sql.
-- Verify after pushing: npm run db:privcheck (section N).
-- ═══════════════════════════════════════════════════════════════

-- 1 ── Reset moment = push moment ───────────────────────────────
do $$
begin
  execute format(
    'create or replace function public.paywall_reset_at() returns timestamptz '
    'language sql immutable set search_path = '''' as $f$ select %L::timestamptz $f$',
    now());
end $$;

grant execute on function public.paywall_reset_at() to anon, authenticated;

-- 2 ── Limit ────────────────────────────────────────────────────
create or replace function public.free_invoice_limit()
returns int
language sql
immutable
set search_path = ''
as $$ select 3 $$;

grant execute on function public.free_invoice_limit() to anon, authenticated;

-- 3 ── Cap trigger ──────────────────────────────────────────────
create or replace function public.enforce_free_invoice_limit()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_tier  text;
  v_count int;
begin
  -- created_at is server-owned (header §4): never trust a client value.
  NEW.created_at := now();

  -- Quotes are never capped.
  if NEW.kind is distinct from 'invoice' then
    return NEW;
  end if;

  -- Tier from the DB for NEW.user_id, never from client input.
  select p.access_tier into v_tier
    from public.profiles p
    where p.id = NEW.user_id;

  if v_tier in ('founder', 'trialing', 'active', 'past_due') then
    return NEW;
  end if;

  -- One capped insert at a time per user, so two concurrent inserts can't
  -- both count the same total and slip under the cap.
  perform pg_advisory_xact_lock(hashtextextended('invoice_cap:' || NEW.user_id::text, 0));

  select count(*) into v_count
    from public.invoices i
    where i.user_id = NEW.user_id
      and i.kind = 'invoice'
      and i.created_at >= public.paywall_reset_at();

  if v_count >= public.free_invoice_limit() then
    -- The hint is what the client keys on to open the paywall.
    raise exception 'Free invoice limit reached'
      using errcode = 'P0001', hint = 'PAYWALL_LIMIT';
  end if;
  return NEW;
end $$;

drop trigger if exists enforce_free_invoice_limit on public.invoices;
create trigger enforce_free_invoice_limit
  before insert on public.invoices
  for each row execute function public.enforce_free_invoice_limit();

-- 4 ── created_at fixed after insert ────────────────────────────
-- Shared with expenses (part 2). Invoker: it only copies OLD into NEW.
create or replace function public.pin_created_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  NEW.created_at := OLD.created_at;
  return NEW;
end $$;

drop trigger if exists pin_created_at on public.invoices;
create trigger pin_created_at
  before update on public.invoices
  for each row execute function public.pin_created_at();

-- Trigger functions are never called directly.
revoke execute on function public.enforce_free_invoice_limit() from public, anon, authenticated;
revoke execute on function public.pin_created_at() from public, anon, authenticated;

$mig1$;

  execute $mig2$
-- ═══════════════════════════════════════════════════════════════
-- Paywall v2, part 2: free expense cap (5), counted from the reset.
--
-- PUSH ON LAUNCH DAY ONLY, together with 20261001000001 (it uses that
-- migration's paywall_reset_at() and pin_created_at()). Live for every user
-- once pushed, whatever NEXT_PUBLIC_PAYWALL_ENABLED says.
--
--   1. free_expense_limit() → 5 (new).
--   2. enforce_free_expense_limit() + BEFORE INSERT trigger on expenses: the
--      mirror of the invoice cap. Counts every expense the user created since
--      paywall_reset_at(), soft-deleted ones included (deleting refunds
--      nothing). Unlimited: founder / trialing / active / past_due. Capped:
--      free, canceled, null, legacy. Raises hint PAYWALL_LIMIT_EXPENSE.
--   3. created_at is server-owned on expenses too: stamped now() on insert
--      by the cap trigger, pinned on update by pin_created_at(). Existing rows
--      are not modified.
--
-- The tier rules must match src/lib/access.ts exactly.
-- Rollback (limits → 1,000,000): supabase/rollbacks/paywall_v2_rollback.sql.
-- Verify after pushing: npm run db:privcheck (section N).
-- ═══════════════════════════════════════════════════════════════

-- 1 ── Limit ────────────────────────────────────────────────────
create or replace function public.free_expense_limit()
returns int
language sql
immutable
set search_path = ''
as $$ select 5 $$;

grant execute on function public.free_expense_limit() to anon, authenticated;

-- 2 ── Cap trigger ──────────────────────────────────────────────
create or replace function public.enforce_free_expense_limit()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_tier  text;
  v_count int;
begin
  -- created_at is server-owned (header §3): never trust a client value.
  NEW.created_at := now();

  select p.access_tier into v_tier
    from public.profiles p
    where p.id = NEW.user_id;

  if v_tier in ('founder', 'trialing', 'active', 'past_due') then
    return NEW;
  end if;

  perform pg_advisory_xact_lock(hashtextextended('expense_cap:' || NEW.user_id::text, 0));

  select count(*) into v_count
    from public.expenses e
    where e.user_id = NEW.user_id
      and e.created_at >= public.paywall_reset_at();

  if v_count >= public.free_expense_limit() then
    raise exception 'Free expense limit reached'
      using errcode = 'P0001', hint = 'PAYWALL_LIMIT_EXPENSE';
  end if;
  return NEW;
end $$;

drop trigger if exists enforce_free_expense_limit on public.expenses;
create trigger enforce_free_expense_limit
  before insert on public.expenses
  for each row execute function public.enforce_free_expense_limit();

-- 3 ── created_at fixed after insert ────────────────────────────
drop trigger if exists pin_created_at on public.expenses;
create trigger pin_created_at
  before update on public.expenses
  for each row execute function public.pin_created_at();

revoke execute on function public.enforce_free_expense_limit() from public, anon, authenticated;

$mig2$;

  execute $mig3$
-- ═══════════════════════════════════════════════════════════════
-- Founder code "JesusisKing": server-only redemption, 25 max, once per user.
--
--   1. Seed the grant: token 'JesusisKing' (stored and matched EXACTLY —
--      case-sensitive, no lowercasing), access_tier 'founder', max_uses 25.
--      access_grants.max_uses / use_count are the redemption cap and count.
--   2. grant_redemptions(grant_id, user_id): one row per user per code, so the
--      same user can't redeem twice. RLS on, no policies, no client
--      privileges: nobody reads it except through the RPC.
--   3. redeem_grant_for(p_user_id, p_token) — SECURITY DEFINER, service_role
--      only. Called by POST /api/redeem (rate-limited, user id from the
--      session). Locks the grant row (FOR UPDATE), so concurrent redemptions
--      serialize and the cap can't be passed. Returns a status:
--        'ok'                — granted
--        'invalid'           — no such code (exact match), expired, or full
--                              (one answer for all three: reveals nothing)
--        'already_founder'   — the user already has founder access
--        'already_redeemed'  — this user already used this code
--        'no_profile'        — the user hasn't finished onboarding
--   4. redeem_grant(text) — the old client-callable RPC — loses client
--      EXECUTE. Codes are redeemed only through /api/redeem from now on, so
--      guessing can't bypass the route's rate limit.
--
-- access_grants itself is unchanged: RLS on, no policies, so clients can't
-- read the code strings or counts. access_tier stays column-locked on
-- profiles; only this SECURITY DEFINER function writes it here.
-- Idempotent. Verify after pushing: npm run db:privcheck (section O).
-- ═══════════════════════════════════════════════════════════════

-- 1 ── The code ─────────────────────────────────────────────────
insert into public.access_grants (token, label, access_tier, max_uses)
values ('JesusisKing', 'JesusisKing founder code', 'founder', 25)
on conflict (token) do nothing;

-- 2 ── One redemption per user per code ─────────────────────────
create table if not exists public.grant_redemptions (
  grant_id    uuid not null references public.access_grants(id) on delete cascade,
  user_id     uuid not null references public.profiles(id) on delete cascade,
  redeemed_at timestamptz not null default now(),
  primary key (grant_id, user_id)
);

alter table public.grant_redemptions enable row level security;
revoke all on public.grant_redemptions from public, anon, authenticated;

-- 3 ── Server-only redemption ───────────────────────────────────
create or replace function public.redeem_grant_for(p_user_id uuid, p_token text)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  g      record;
  v_tier text;
begin
  if p_user_id is null or p_token is null
     or char_length(p_token) < 3 or char_length(p_token) > 40 then
    return 'invalid';
  end if;

  -- Lock the caller's profile first: one redemption at a time per user.
  select p.access_tier into v_tier
    from public.profiles p
    where p.id = p_user_id
    for update;
  if not found then
    return 'no_profile';
  end if;
  if v_tier = 'founder' then
    return 'already_founder';
  end if;

  -- Exact, case-sensitive match. FOR UPDATE serializes concurrent
  -- redemptions of the same code, so use_count can't pass max_uses.
  select * into g
    from public.access_grants a
    where a.token = p_token
    for update;
  if not found
     or (g.expires_at is not null and g.expires_at < now())
     or (g.max_uses is not null and g.use_count >= g.max_uses) then
    return 'invalid';
  end if;

  if exists (select 1 from public.grant_redemptions r
             where r.grant_id = g.id and r.user_id = p_user_id) then
    return 'already_redeemed';
  end if;

  insert into public.grant_redemptions (grant_id, user_id) values (g.id, p_user_id);
  update public.access_grants set use_count = use_count + 1 where id = g.id;
  update public.profiles
    set access_tier = g.access_tier, granted_via = g.token
    where id = p_user_id;
  return 'ok';
end $$;

revoke execute on function public.redeem_grant_for(uuid, text) from public, anon, authenticated;
grant execute on function public.redeem_grant_for(uuid, text) to service_role;

-- 4 ── The old client-callable RPC: no client access ────────────
revoke execute on function public.redeem_grant(text) from public, anon, authenticated;

$mig3$;

  -- ── Throwaway users (random ids: never a real account) ──────
  insert into auth.users (id, email) values
    (free_u, 'paywall-validation-free-' || free_u || '@example.invalid'),
    (founder_u, 'paywall-validation-founder-' || founder_u || '@example.invalid');
  insert into public.profiles (id, business_name, access_tier) values
    (free_u, 'Paywall validation (free)', 'free'),
    (founder_u, 'Paywall validation (founder)', 'founder');

  -- ── Free user: invoices (free limit 3) ─────────────────────
  begin
    insert into public.invoices (user_id, client_name, kind) values (free_u, 'Validation client 1', 'invoice');
    insert into public.invoices (user_id, client_name, kind) values (free_u, 'Validation client 2', 'invoice');
    insert into public.invoices (user_id, client_name, kind) values (free_u, 'Validation client 3', 'invoice');
    report := array_append(report, 'PASS  free: invoices 1-3 allowed'); passed := passed + 1;
  exception when others then
    report := array_append(report, ('FAIL  free: invoices 1-3 rejected: ' || sqlerrm)); failed := failed + 1;
  end;

  begin
    insert into public.invoices (user_id, client_name, kind) values (free_u, 'Validation client 4', 'invoice');
    report := array_append(report, 'FAIL  free: 4th invoice was ALLOWED'); failed := failed + 1;
  exception when others then
    get stacked diagnostics v_hint = pg_exception_hint;
    if v_hint = 'PAYWALL_LIMIT' then
      report := array_append(report, 'PASS  free: 4th invoice rejected (PAYWALL_LIMIT)'); passed := passed + 1;
    else
      report := array_append(report, ('FAIL  free: 4th invoice rejected for the wrong reason: ' || sqlerrm)); failed := failed + 1;
    end if;
  end;

  begin
    insert into public.invoices (user_id, client_name, kind) values (free_u, 'Validation quote', 'quote');
    report := array_append(report, 'PASS  free: quote allowed past the invoice cap (quotes never count)'); passed := passed + 1;
  exception when others then
    report := array_append(report, ('FAIL  free: quote rejected: ' || sqlerrm)); failed := failed + 1;
  end;

  -- ── Free user: expenses (free limit 5; soft delete refunds nothing) ──
  begin
    insert into public.expenses (user_id, amount) values (free_u, 10);
    insert into public.expenses (user_id, amount) values (free_u, 20);
    insert into public.expenses (user_id, amount) values (free_u, 30);
    insert into public.expenses (user_id, amount) values (free_u, 40);
    insert into public.expenses (user_id, amount) values (free_u, 50) returning id into v_id;
    update public.expenses set deleted_at = now() where id = v_id;
    report := array_append(report, 'PASS  free: expenses 1-5 allowed (5th then soft-deleted)'); passed := passed + 1;
  exception when others then
    report := array_append(report, ('FAIL  free: expenses 1-5 rejected: ' || sqlerrm)); failed := failed + 1;
  end;

  begin
    insert into public.expenses (user_id, amount) values (free_u, 60);
    report := array_append(report, 'FAIL  free: 6th expense was ALLOWED (soft-deleted row must still count)'); failed := failed + 1;
  exception when others then
    get stacked diagnostics v_hint = pg_exception_hint;
    if v_hint = 'PAYWALL_LIMIT_EXPENSE' then
      report := array_append(report, 'PASS  free: 6th expense rejected (PAYWALL_LIMIT_EXPENSE), soft-deleted row still counted'); passed := passed + 1;
    else
      report := array_append(report, ('FAIL  free: 6th expense rejected for the wrong reason: ' || sqlerrm)); failed := failed + 1;
    end if;
  end;

  -- ── Founder: unlimited (past both free limits) ──────────────
  begin
    insert into public.invoices (user_id, client_name, kind) values (founder_u, 'Founder client 1', 'invoice');
    insert into public.invoices (user_id, client_name, kind) values (founder_u, 'Founder client 2', 'invoice');
    insert into public.invoices (user_id, client_name, kind) values (founder_u, 'Founder client 3', 'invoice');
    insert into public.invoices (user_id, client_name, kind) values (founder_u, 'Founder client 4', 'invoice');
    report := array_append(report, 'PASS  founder: 4 invoices allowed'); passed := passed + 1;
  exception when others then
    report := array_append(report, ('FAIL  founder: invoice rejected: ' || sqlerrm)); failed := failed + 1;
  end;

  begin
    insert into public.expenses (user_id, amount) values (founder_u, 1);
    insert into public.expenses (user_id, amount) values (founder_u, 2);
    insert into public.expenses (user_id, amount) values (founder_u, 3);
    insert into public.expenses (user_id, amount) values (founder_u, 4);
    insert into public.expenses (user_id, amount) values (founder_u, 5);
    insert into public.expenses (user_id, amount) values (founder_u, 6);
    report := array_append(report, 'PASS  founder: 6 expenses allowed'); passed := passed + 1;
  exception when others then
    report := array_append(report, ('FAIL  founder: expense rejected: ' || sqlerrm)); failed := failed + 1;
  end;

  -- ── created_at can't be backdated (insert or update) ────────
  begin
    insert into public.expenses (user_id, amount, created_at) values (founder_u, 4, '2000-01-01')
      returning id, created_at into v_id, v_ts;
    if v_ts >= public.paywall_reset_at() then
      report := array_append(report, 'PASS  backdated created_at on insert is replaced by now()'); passed := passed + 1;
    else
      report := array_append(report, ('FAIL  insert kept backdated created_at ' || v_ts)); failed := failed + 1;
    end if;
    update public.expenses set created_at = '2000-01-01' where id = v_id returning created_at into v_ts;
    if v_ts >= public.paywall_reset_at() then
      report := array_append(report, 'PASS  created_at unchanged by update (expenses)'); passed := passed + 1;
    else
      report := array_append(report, ('FAIL  expense update backdated created_at to ' || v_ts)); failed := failed + 1;
    end if;
    update public.invoices set created_at = '2000-01-01'
      where id = (select id from public.invoices where user_id = founder_u limit 1)
      returning created_at into v_ts;
    if v_ts >= public.paywall_reset_at() then
      report := array_append(report, 'PASS  created_at unchanged by update (invoices)'); passed := passed + 1;
    else
      report := array_append(report, ('FAIL  invoice update backdated created_at to ' || v_ts)); failed := failed + 1;
    end if;
  exception when others then
    report := array_append(report, ('FAIL  created_at checks errored: ' || sqlerrm)); failed := failed + 1;
  end;

  -- ══ Rollback lifts the caps ═════════════════════════════════
  -- The free user is at 3 invoices + 5 expenses (one soft-deleted) here.
  execute $rollback$
-- ═══════════════════════════════════════════════════════════════
-- Paywall v2 ROLLBACK — turns the free caps off again (limits → 1,000,000).
--
-- Use only if launch goes wrong. NOT in supabase/migrations on purpose: a file
-- there would be applied by the next db push. To apply (CLAUDE.md flow):
--   1. Copy this file to supabase/migrations/<YYYYMMDDHHMMSS>_paywall_rollback.sql
--      with a timestamp newer than every existing migration.
--   2. npx supabase db push --dry-run, show the SQL, get the user's yes.
--   3. npx supabase db push, then npm run db:privcheck.
-- Also set NEXT_PUBLIC_PAYWALL_ENABLED=false (Production) and redeploy so the
-- UI stops showing upgrade prompts.
--
-- Same kill-switch value as 20260823120000, for invoices and expenses.
-- Triggers, paywall_reset_at() and the created_at pinning stay in place; with
-- limits this high nobody is capped.
-- Re-enabling later = a new migration setting the limits back.
-- ═══════════════════════════════════════════════════════════════

create or replace function public.free_invoice_limit()
returns int
language sql
immutable
set search_path = ''
as $$ select 1000000 $$;

grant execute on function public.free_invoice_limit() to anon, authenticated;

-- free_expense_limit() exists once 20261001000002 is pushed; with the limit
-- at 1,000,000 the expense trigger never fires either.
create or replace function public.free_expense_limit()
returns int
language sql
immutable
set search_path = ''
as $$ select 1000000 $$;

grant execute on function public.free_expense_limit() to anon, authenticated;

$rollback$;

  begin
    insert into public.invoices (user_id, client_name, kind) values (free_u, 'Validation client 4 (after rollback)', 'invoice');
    report := array_append(report, 'PASS  rollback: free user''s 4th invoice now allowed'); passed := passed + 1;
  exception when others then
    report := array_append(report, ('FAIL  rollback: 4th invoice still rejected: ' || sqlerrm)); failed := failed + 1;
  end;

  begin
    insert into public.expenses (user_id, amount) values (free_u, 60);
    report := array_append(report, 'PASS  rollback: free user''s 6th expense now allowed'); passed := passed + 1;
  exception when others then
    report := array_append(report, ('FAIL  rollback: 6th expense still rejected: ' || sqlerrm)); failed := failed + 1;
  end;

  -- ══ Founder code (20261001000003) ═══════════════════════════
  insert into auth.users (id, email) values
    (code_u1, 'paywall-validation-code1-' || code_u1 || '@example.invalid'),
    (code_u2, 'paywall-validation-code2-' || code_u2 || '@example.invalid'),
    (code_u3, 'paywall-validation-code3-' || code_u3 || '@example.invalid');
  insert into public.profiles (id, business_name, access_tier) values
    (code_u1, 'Paywall validation (code 1)', 'free'),
    (code_u2, 'Paywall validation (code 2)', 'free'),
    (code_u3, 'Paywall validation (code 3)', 'canceled');

  -- Exact match grants founder.
  v_status := public.redeem_grant_for(code_u1, 'JesusisKing');
  select access_tier, granted_via into v_tier, v_text from public.profiles where id = code_u1;
  if v_status = 'ok' and v_tier = 'founder' and v_text = 'JesusisKing' then
    report := array_append(report, 'PASS  code: exact "JesusisKing" redeemed, tier founder'); passed := passed + 1;
  else
    report := array_append(report, format('FAIL  code: exact match -> %s, tier %s, via %s', v_status, v_tier, v_text)); failed := failed + 1;
  end if;

  -- Wrong case is rejected (and costs nothing).
  v_status := public.redeem_grant_for(code_u2, 'jesusisking');
  select access_tier into v_tier from public.profiles where id = code_u2;
  if v_status = 'invalid' and v_tier = 'free' then
    report := array_append(report, 'PASS  code: "jesusisking" (wrong case) rejected'); passed := passed + 1;
  else
    report := array_append(report, format('FAIL  code: wrong case -> %s, tier %s', v_status, v_tier)); failed := failed + 1;
  end if;

  -- An existing founder is refused (doesn't burn a use).
  select use_count into v_count from public.access_grants where token = 'JesusisKing';
  v_status := public.redeem_grant_for(founder_u, 'JesusisKing');
  if v_status = 'already_founder'
     and (select use_count from public.access_grants where token = 'JesusisKing') = v_count then
    report := array_append(report, 'PASS  code: existing founder refused, no use spent'); passed := passed + 1;
  else
    report := array_append(report, ('FAIL  code: existing founder -> ' || v_status)); failed := failed + 1;
  end if;

  -- Repeat redemption by the same user is rejected even if they lost founder.
  update public.profiles set access_tier = 'free' where id = code_u1;
  v_status := public.redeem_grant_for(code_u1, 'JesusisKing');
  if v_status = 'already_redeemed' then
    report := array_append(report, 'PASS  code: repeat redemption by the same user rejected'); passed := passed + 1;
  else
    report := array_append(report, ('FAIL  code: repeat redemption -> ' || v_status)); failed := failed + 1;
  end if;

  -- Cap: a throwaway code with max_uses = 1.
  insert into public.access_grants (token, label, access_tier, max_uses)
    values ('ValidationCap1', 'validation cap test', 'founder', 1);
  v_status := public.redeem_grant_for(code_u2, 'ValidationCap1');
  v_text := public.redeem_grant_for(code_u3, 'ValidationCap1');
  select use_count into v_count from public.access_grants where token = 'ValidationCap1';
  if v_status = 'ok' and v_text = 'invalid' and v_count = 1 then
    report := array_append(report, 'PASS  code: cap enforced (1st of max_uses=1 ok, 2nd rejected, use_count 1)'); passed := passed + 1;
  else
    report := array_append(report, format('FAIL  code: cap -> first %s, second %s, use_count %s', v_status, v_text, v_count)); failed := failed + 1;
  end if;

  -- ── As a real client (role authenticated, a session for code_u3) ──
  begin
    perform set_config('request.jwt.claims',
      json_build_object('sub', code_u3, 'role', 'authenticated')::text, true);
    execute 'set local role authenticated';

    begin
      perform public.redeem_grant_for(code_u3, 'JesusisKing');
      report := array_append(report, 'FAIL  client: redeem_grant_for is EXECUTABLE by authenticated'); failed := failed + 1;
    exception when insufficient_privilege then
      report := array_append(report, 'PASS  client: redeem_grant_for not executable'); passed := passed + 1;
    end;

    begin
      perform public.redeem_grant('JesusisKing');
      report := array_append(report, 'FAIL  client: redeem_grant is EXECUTABLE by authenticated'); failed := failed + 1;
    exception when insufficient_privilege then
      report := array_append(report, 'PASS  client: redeem_grant (old RPC) not executable'); passed := passed + 1;
    end;

    begin
      select count(*) into v_count from public.access_grants;
      if v_count = 0 then
        report := array_append(report, 'PASS  client: access_grants returns no rows (codes and counts hidden)'); passed := passed + 1;
      else
        report := array_append(report, ('FAIL  client: can read ' || v_count || ' access_grants rows')); failed := failed + 1;
      end if;
    exception when insufficient_privilege then
      report := array_append(report, 'PASS  client: access_grants not readable'); passed := passed + 1;
    end;

    begin
      update public.access_grants set max_uses = 1000000;
      get diagnostics v_rows = row_count;
      if v_rows = 0 then
        report := array_append(report, 'PASS  client: access_grants can''t be changed (0 rows updated)'); passed := passed + 1;
      else
        report := array_append(report, ('FAIL  client: updated ' || v_rows || ' access_grants rows')); failed := failed + 1;
      end if;
    exception when insufficient_privilege then
      report := array_append(report, 'PASS  client: access_grants can''t be changed'); passed := passed + 1;
    end;

    begin
      select count(*) into v_count from public.grant_redemptions;
      report := array_append(report, ('FAIL  client: grant_redemptions is readable (' || v_count || ' rows)')); failed := failed + 1;
    exception when insufficient_privilege then
      report := array_append(report, 'PASS  client: grant_redemptions not readable'); passed := passed + 1;
    end;

    execute 'reset role';
  exception when others then
    execute 'reset role';
    report := array_append(report, ('FAIL  client checks errored: ' || sqlerrm)); failed := failed + 1;
  end;

  -- ── Report, then roll everything back ───────────────────────
  -- The count lines make a silently skipped test visible: a block that dies
  -- early reports fewer lines than expected.
  raise exception '%', format(
    E'PAYWALL VALIDATION: %s passed, %s failed, %s expected%s (everything rolled back)\n%s\nTOTAL: PASS %s / FAIL %s / expected %s%s',
    passed, failed, 22,
    case when passed + failed <> 22 then ' — COUNT MISMATCH' else '' end,
    array_to_string(report, E'\n'),
    passed, failed, 22,
    case when passed + failed <> 22 then ' — COUNT MISMATCH: a test did not report' else '' end);
end
$validate$;
