'use client';
// HTML → canvas → PDF. Renders the chosen template offscreen at A4 size,
// captures it, and returns a File ready for the native share sheet.
// Filename format: <PREFIX>-####_ClientName_Date_BusinessName.pdf — INV- for
// invoices (locked), Q- for quotes, so the two are distinct in the share sheet
// and the Vault.
import html2canvas from 'html2canvas';
import { jsPDF } from 'jspdf';
import { docPrefix } from '@/lib/documents';

const safe = (s: string) => s.replace(/[^a-z0-9]+/gi, '').slice(0, 24) || 'Client';

export function invoiceFilename(kind: string, no: number, client: string, business: string, date = new Date()) {
  const d = date.toISOString().slice(0, 10);
  return `${docPrefix(kind)}-${String(no).padStart(4, '0')}_${safe(client)}_${d}_${safe(business)}.pdf`;
}

/** Filename for the expense-summary export, e.g.
 *  Expense-Summary_2026_AcmePlumbing.pdf (totals), or itemized:
 *  Expense-Summary-Itemized_2026_AcmePlumbing.pdf */
export function summaryFilename(periodLabel: string, business: string, itemized = false) {
  return `Expense-Summary${itemized ? '-Itemized' : ''}_${safe(periodLabel)}_${safe(business)}.pdf`;
}

export function incomeSummaryFilename(periodLabel: string, business: string, itemized = false) {
  return `Income-Summary${itemized ? '-Itemized' : ''}_${safe(periodLabel)}_${safe(business)}.pdf`;
}

/** Wait for every <img> inside the node to finish decoding. html2canvas does not
 *  wait, so a slow logo (Supabase storage) rasterizes as a blank box. decode()
 *  rejects on a broken image — we swallow that so one bad logo can't block the
 *  whole document. */
async function awaitImages(el: HTMLElement): Promise<void> {
  const imgs = Array.from(el.querySelectorAll('img'));
  await Promise.all(
    imgs.map((img) =>
      img.complete && img.naturalWidth > 0
        ? Promise.resolve()
        : img.decode().catch(() => undefined)
    )
  );
}

/** Measures data-pdf-link nodes in pageEl and attaches jsPDF link annotations to the active page */
function addPageLinks(pdf: jsPDF, pageEl: HTMLElement) {
  const elRect = pageEl.getBoundingClientRect();
  if (elRect.width <= 0) return;
  const ratio = 794 / elRect.width;
  pageEl.querySelectorAll<HTMLElement>('[data-pdf-link]').forEach((node) => {
    const url = node.dataset.pdfLink;
    if (!url) return;
    const r = node.getBoundingClientRect();
    pdf.link(
      (r.left - elRect.left) * ratio,
      (r.top - elRect.top) * ratio,
      r.width * ratio,
      r.height * ratio,
      { url }
    );
  });
}

const PAGE_H = 1123;
// Clear space kept between flow content and a footer line pinned to the page
// bottom (Classic's "Thank you for your business.", "Generated by On It").
const FOOTER_GAP = 8;

const px = (v: string) => parseFloat(v) || 0;
const isClear = (cs: CSSStyleDeclaration) =>
  (cs.backgroundColor === 'rgba(0, 0, 0, 0)' || cs.backgroundColor === 'transparent') &&
  cs.backgroundImage === 'none' &&
  px(cs.borderBottomWidth) === 0;

/** Where flow content may end on a page, and where it actually ends, both in
 *  px from the page top. `root` is the page box: a template root (page 1, or
 *  the single-page document) or a continuation page node.
 *  - limit: the page's real bottom padding (the root's own, plus a clear
 *    full-width wrapper's — Industrial pads its body, not its root), and
 *    FOOTER_GAP above any line pinned to the page bottom (position: absolute).
 *    Footers are placed as on a 1123px page, whatever the root's height now.
 *  - bottom: the lowest in-flow child, minus a clear wrapper's bottom padding.
 *    Zero-height children (a wrapper whose block moved to a later page) are
 *    skipped: they hold no ink, and so is a data-pdf-footer-spacer (flow room
 *    a template keeps for its pinned footer, which is counted itself here).
 *  skipAbsBlocks: leave out pinned footers that are data-pdf-blocks (the books
 *  summaries' footer) — for page 1 of a split, which they leave for the final
 *  page. */
function measurePage(root: HTMLElement, { skipAbsBlocks = false } = {}): { limit: number; bottom: number } {
  const rr = root.getBoundingClientRect();
  const rcs = getComputedStyle(root);
  let inset = px(rcs.paddingBottom) + px(rcs.borderBottomWidth);
  let wrapperPad = 0;
  let footerTop = PAGE_H;
  let bottom = 0;
  Array.from(root.children).forEach((node) => {
    const c = node as HTMLElement;
    const cs = getComputedStyle(c);
    if (cs.display === 'none') return;
    const r = c.getBoundingClientRect();
    if (r.height === 0 || c.hasAttribute('data-pdf-footer-spacer')) return;
    if (cs.position === 'absolute' || cs.position === 'fixed') {
      if (skipAbsBlocks && c.hasAttribute('data-pdf-block')) return;
      footerTop = Math.min(footerTop, PAGE_H - (rr.bottom - r.top));
      return;
    }
    const pad = isClear(cs) ? px(cs.paddingBottom) : 0;
    wrapperPad = Math.max(wrapperPad, pad);
    bottom = Math.max(bottom, r.bottom - rr.top - pad);
  });
  inset += wrapperPad;
  return { limit: Math.min(PAGE_H - inset, footerTop - FOOTER_GAP), bottom };
}

/** el = the rendered template node (794px wide).
 *  PNG, not JPEG: flat color with fine text, often on near-black background.
 *  scale: capture resolution. 3 (the default, every invoice) for crisp text
 *  edges; the books summaries pass 2, which keeps black-on-white text crisp at
 *  100% while cutting capture time and memory on long multi-page documents.
 *  backgroundColor: null so templates paint their own background.
 *  Multi-page documents are measured and partitioned by DOM block rather than canvas-sliced,
 *  preserving split-free table rows and page-specific link annotations.
 *
 *  Page model: the one table's rows are packed page by page (page 1 under the
 *  masthead, then continuation pages under a short header). The last-page
 *  blocks (data-pdf-block: totals, How to pay, notes, the summaries' total)
 *  then follow the last rows one at a time, totals first, as many as fit;
 *  the rest start a page of their own with no table on it. Each placement is
 *  checked by laying the real page out offscreen and measuring it. */
export async function elementToPdf(el: HTMLElement, filename: string, { scale = 3 }: { scale?: number } = {}): Promise<File> {
  // Wait for web fonts before capture: html2canvas snapshots synchronously and
  // uses fallback-font metrics if the display font isn't ready yet, which
  // collapses letter spacing. Guarded — document.fonts is absent in older envs.
  if (typeof document !== 'undefined' && document.fonts?.ready) {
    await document.fonts.ready;
  }
  await awaitImages(el);

  const fullHeight = el.scrollHeight || el.offsetHeight;
  const table = el.querySelector('table');
  const rows = table ? Array.from(table.querySelectorAll<HTMLElement>('tbody tr')) : [];
  const totalRows = rows.length;

  // The page model paginates ONE table: everything above it is page-1 content,
  // everything below it moves to the last page. A second table would never be
  // split, so a long one would be clipped. Every template today has exactly one
  // (invoices, quotes and all four books PDFs); say so loudly if that changes.
  if (el.querySelectorAll('table').length > 1) {
    console.warn(`elementToPdf(${filename}): ${el.querySelectorAll('table').length} tables — only the first paginates`);
  }

  // Page geometry, measured on the template itself (see measurePage).
  const root = (el.firstElementChild as HTMLElement | null) ?? el;
  // page1: the whole document on one page, every pinned footer counted.
  const page1 = measurePage(root);
  const rootTop = root.getBoundingClientRect().top;

  // ── Last-page blocks ──────────────────────────────────────────
  // Indexed by document order, which a clone of el shares. The Ledger rail
  // stays on page 1 only. A block that is itself absolutely positioned (the
  // summaries' footer) is page furniture: it goes on the final page, whatever
  // that turns out to be. The rest flow, placed in units: totals first, then
  // document order; a block marked data-pdf-keep-with-prev (Ledger's closing
  // line) always travels with the unit before it.
  const allBlocks = Array.from(el.querySelectorAll<HTMLElement>('[data-pdf-block]'));
  const kindOf = (i: number) => allBlocks[i].getAttribute('data-pdf-block');
  const isAbs = (i: number) => ['absolute', 'fixed'].includes(getComputedStyle(allBlocks[i]).position);
  const isTotals = (i: number) => kindOf(i) === 'totals' || kindOf(i) === 'total';
  const movable = allBlocks.map((_, i) => i).filter((i) => kindOf(i) !== 'ledger-rail');
  const absBlocks = movable.filter(isAbs);
  const flowBlocks = movable.filter((i) => !isAbs(i));
  const units: number[][] = [];
  [...flowBlocks.filter(isTotals), ...flowBlocks.filter((i) => !isTotals(i))].forEach((i) => {
    if (units.length && allBlocks[i].hasAttribute('data-pdf-keep-with-prev')) units[units.length - 1].push(i);
    else units.push([i]);
  });

  // Single-page fast path: content ends above the template's own bottom limit,
  // or there is nothing to move to a second page
  if (page1.bottom <= page1.limit || (totalRows <= 1 && units.length === 0)) {
    if (page1.bottom > page1.limit) {
      // Taller than a page with nothing to split across pages: it is drawn into
      // one page box and the overflow is clipped. No template produces this
      // today; the warning makes a future one visible instead of silent.
      console.warn(`elementToPdf(${filename}): ${fullHeight}px of content with ${totalRows} table row(s) — clipped to one page`);
    }
    const canvas = await html2canvas(el, { scale, useCORS: true, backgroundColor: null });
    const pdf = new jsPDF({ unit: 'px', format: [794, 1123], compress: true });
    pdf.addImage(canvas.toDataURL('image/png'), 'PNG', 0, 0, 794, 1123);
    addPageLinks(pdf, el);
    const blob = pdf.output('blob');
    return new File([blob], filename, { type: 'application/pdf' });
  }

  // ── Multi-page DOM Block Partitioning ──────────────────────────
  const rowHeights = rows.map((r) => r.offsetHeight || 36);
  // Opt-in keep-with-next (summary group headers, a payment above its line
  // items): a page never ends on a row marked data-pdf-keep-with-next. The page
  // break moves up to before the marked run, keeping at least one row per page.
  // Invoice templates don't set it, so their pagination is unchanged.
  const keepWithNext = rows.map((r) => r.hasAttribute('data-pdf-keep-with-next'));
  const backOffKept = (start: number, end: number) => {
    let e = end;
    while (e < totalRows && e - start > 1 && keepWithNext[e - 1]) e--;
    return e;
  };
  // Opt-in groups (summary documents: a client or a category). Every row of a
  // group carries data-pdf-group="<id>"; its header row also carries
  // data-pdf-group-header, with the name in [data-pdf-group-name]. A page that
  // opens mid-group starts with a copy of that header reading "<Name>
  // (continued)" (parts marked data-pdf-continued-hide — counts, subtotals —
  // dropped), and its height is reserved when the page is packed. When the
  // page opens on a row carrying data-pdf-continued-suffix (a line item under
  // its invoice), the suffix joins the name: "<Name> · INV-1076 (continued)".
  // A break between payments keeps the name-only form.
  const groupOf = rows.map((r) => r.getAttribute('data-pdf-group'));
  const groupHeaderIdx = new Map<string, number>();
  rows.forEach((r, i) => {
    const g = groupOf[i];
    if (g && r.hasAttribute('data-pdf-group-header') && !groupHeaderIdx.has(g)) groupHeaderIdx.set(g, i);
  });
  /** Index of the header to repeat as "(continued)" when a page starts at row i, or -1. */
  const continuedHeaderFor = (i: number) => {
    const g = groupOf[i];
    if (!g || i === 0 || groupOf[i - 1] !== g || rows[i].hasAttribute('data-pdf-group-header')) return -1;
    return groupHeaderIdx.get(g) ?? -1;
  };
  const tableHeader = table?.querySelector('thead') as HTMLElement | null;

  const { bg: computedBg, color: computedColor, fontFamily: computedFont } = getEffectiveBgAndColor(el);

  const businessName = el.querySelector('[data-pdf-business-name]')?.textContent?.trim() || '';
  const docNounStr = el.querySelector('[data-pdf-doc-noun]')?.textContent?.trim() || '';
  const docNumStr = el.querySelector('[data-pdf-doc-number]')?.textContent?.trim() || '';
  const docMark = (docNounStr && docNumStr) ? `${docNounStr} ${docNumStr}` : (docNounStr || docNumStr || 'INVOICE');

  /** One page: rows [start, end) of the table, then `blocks` (indices into
   *  allBlocks) in that order. `final` adds the absolutely positioned blocks. */
  type Page = { start: number; end: number; blocks: number[] };

  const pageIndicator = (label: string) => {
    const pageInd = document.createElement('div');
    pageInd.style.position = 'absolute';
    pageInd.style.right = '56px';
    pageInd.style.bottom = '14px';
    pageInd.style.fontSize = '11px';
    pageInd.style.opacity = '0.7';
    pageInd.textContent = label;
    return pageInd;
  };

  const buildFirstPage = (page: Page, final: boolean, label: string | null) => {
    // Page 1: Clone el content cleanly at full 794x1123 size
    const pageNode = document.createElement('div');
    pageNode.style.width = '794px';
    pageNode.style.height = '1123px';
    pageNode.style.boxSizing = 'border-box';
    pageNode.style.position = 'relative';
    pageNode.style.overflow = 'hidden';
    pageNode.style.backgroundColor = computedBg;
    pageNode.style.color = computedColor;
    pageNode.style.fontFamily = computedFont;
    pageNode.style.padding = '0px';

    const clone = el.cloneNode(true) as HTMLElement;
    clone.style.width = '794px';
    clone.style.minHeight = '1123px';
    clone.style.height = '1123px';
    clone.style.boxSizing = 'border-box';
    clone.style.backgroundColor = computedBg;
    clone.style.color = computedColor;

    if (clone.firstElementChild) {
      const templateRoot = clone.firstElementChild as HTMLElement;
      templateRoot.style.width = '794px';
      templateRoot.style.minHeight = '1123px';
      templateRoot.style.height = '1123px';
      templateRoot.style.boxSizing = 'border-box';
      templateRoot.style.backgroundColor = computedBg;
    }

    // Hide rows not belonging to Page 1
    const cloneTable = clone.querySelector('table');
    if (cloneTable) {
      const cloneRows = Array.from(cloneTable.querySelectorAll('tbody tr'));
      cloneRows.forEach((r, idx) => {
        if (idx < page.start || idx >= page.end) {
          r.remove();
        }
      });
    }

    // Drop the blocks that print on a later page. The Ledger rail always stays.
    clone.querySelectorAll('[data-pdf-block]').forEach((b, i) => {
      const keep = kindOf(i) === 'ledger-rail' || page.blocks.includes(i) || (final && absBlocks.includes(i));
      if (!keep) b.remove();
    });

    if (label) clone.appendChild(pageIndicator(label));

    pageNode.appendChild(clone);
    return pageNode;
  };

  const buildContinuationPage = (page: Page, final: boolean, label: string) => {
    // Page 2+: Build continuation page
    const pageNode = document.createElement('div');
    pageNode.style.width = '794px';
    pageNode.style.height = '1123px';
    pageNode.style.boxSizing = 'border-box';
    pageNode.style.position = 'relative';
    pageNode.style.overflow = 'hidden';
    pageNode.style.backgroundColor = computedBg;
    pageNode.style.color = computedColor;
    pageNode.style.fontFamily = computedFont;
    pageNode.style.padding = '48px 56px';

    // 1. Continuation Header (Business name + document number only, ~50% masthead height)
    const contHeader = document.createElement('div');
    contHeader.style.display = 'flex';
    contHeader.style.justifyContent = 'space-between';
    contHeader.style.alignItems = 'center';
    contHeader.style.paddingBottom = '12px';
    contHeader.style.marginBottom = '20px';
    contHeader.style.borderBottom = `1px solid ${computedColor}33`;

    const leftHead = document.createElement('div');
    leftHead.style.fontWeight = '800';
    leftHead.style.fontSize = '16px';
    leftHead.style.lineHeight = '1.2';
    leftHead.style.color = computedColor;
    leftHead.textContent = businessName;

    const rightHead = document.createElement('div');
    rightHead.style.fontSize = '12px';
    rightHead.style.fontWeight = '700';
    rightHead.style.letterSpacing = '0.08em';
    rightHead.style.textTransform = 'uppercase';
    rightHead.style.opacity = '0.8';
    rightHead.style.color = computedColor;
    rightHead.textContent = docMark;

    contHeader.appendChild(leftHead);
    contHeader.appendChild(rightHead);
    pageNode.appendChild(contHeader);

    // 2. Table with repeated header and assigned rows — only when this page
    // carries rows: a page of blocks alone (How to pay after a full page 1)
    // has no table.
    const hasRows = table && page.end > page.start;
    if (hasRows) {
      const pageTable = document.createElement('table');
      pageTable.style.width = '100%';
      pageTable.style.borderCollapse = 'collapse';
      pageTable.style.fontSize = '15px';
      // Carry the template's explicit line-height (summary documents set one)
      // so rows measure and paint the same as on page 1.
      pageTable.style.lineHeight = (table as HTMLElement).style.lineHeight;
      // ...and its table-layout, so a fixed-layout table wraps rows to the
      // same widths (and so the same measured heights) on every page.
      pageTable.style.tableLayout = (table as HTMLElement).style.tableLayout;

      if (tableHeader) {
        pageTable.appendChild(tableHeader.cloneNode(true));
      }

      const tbody = document.createElement('tbody');
      const contIdx = continuedHeaderFor(page.start);
      if (contIdx >= 0) {
        const cont = rows[contIdx].cloneNode(true) as HTMLElement;
        cont.removeAttribute('data-pdf-keep-with-next');
        cont.querySelectorAll('[data-pdf-continued-hide]').forEach((n) => n.remove());
        const name = cont.querySelector('[data-pdf-group-name]');
        const suffix = rows[page.start].getAttribute('data-pdf-continued-suffix');
        if (name) name.textContent = `${name.textContent ?? ''}${suffix ? ` · ${suffix}` : ''} (continued)`;
        tbody.appendChild(cont);
      }
      for (let rIdx = page.start; rIdx < page.end; rIdx++) {
        if (rows[rIdx]) {
          tbody.appendChild(rows[rIdx].cloneNode(true));
        }
      }
      pageTable.appendChild(tbody);
      pageNode.appendChild(pageTable);
    }

    // 3. This page's trailing blocks (Totals, PaymentBlock, Notes), in placement order
    if (page.blocks.length > 0) {
      const trailingWrapper = document.createElement('div');
      trailingWrapper.style.marginTop = hasRows ? '24px' : '0px';
      trailingWrapper.style.display = 'flex';
      trailingWrapper.style.flexDirection = 'column';
      trailingWrapper.style.gap = '20px';

      page.blocks.forEach((i) => {
        trailingWrapper.appendChild(allBlocks[i].cloneNode(true));
      });
      pageNode.appendChild(trailingWrapper);
    }

    // Absolutely positioned blocks (the summaries' footer) sit directly on the
    // final page, so they position against it and measurePage sees them.
    if (final) {
      absBlocks.forEach((i) => pageNode.appendChild(allBlocks[i].cloneNode(true)));
    }

    // Ledger special case (PDF-SPEC 6.5 & 9.4): drop payment rail on pages 2+
    pageNode.querySelectorAll('[data-pdf-block="ledger-rail"]').forEach((rail) => rail.remove());

    // 4. Page N of M Indicator
    pageNode.appendChild(pageIndicator(label));
    return pageNode;
  };

  const buildPage = (page: Page, index: number, final: boolean, label: string | null) =>
    index === 0 ? buildFirstPage(page, final, label) : buildContinuationPage(page, final, label ?? '');

  const offscreenContainer = document.createElement('div');
  offscreenContainer.style.position = 'fixed';
  offscreenContainer.style.left = '-9999px';
  offscreenContainer.style.top = '0px';
  document.body.appendChild(offscreenContainer);
  // Everything from here to the PDF output runs inside try/finally so a
  // failed capture (html2canvas throwing mid-page) can't leave the offscreen
  // container on the page.
  try {
    /** Lay the page out offscreen and check its content ends above its limit.
     *  The indicator text is a stand-in; only its box matters here. */
    const fits = (page: Page, index: number, final: boolean) => {
      const node = buildPage(page, index, final, 'Page 1 of 2');
      offscreenContainer.appendChild(node);
      const target = index === 0
        ? ((node.firstElementChild?.firstElementChild as HTMLElement | null) ?? node)
        : node;
      const m = measurePage(target);
      node.remove();
      return m.bottom <= m.limit;
    };

    // Continuation pages: where their first row starts and where content must
    // end, measured on a probe page holding row 0.
    let continuationCapacity = 0;
    if (totalRows > 0) {
      const probe = buildContinuationPage({ start: 0, end: 1, blocks: [] }, false, 'Page 1 of 2');
      offscreenContainer.appendChild(probe);
      const firstRow = probe.querySelector('tbody tr') as HTMLElement | null;
      const rowTop = firstRow ? firstRow.getBoundingClientRect().top - probe.getBoundingClientRect().top : 0;
      continuationCapacity = Math.max(300, measurePage(probe).limit - rowTop);
      probe.remove();
    }

    // Partition row indices into pages
    const pages: Page[] = [];

    // Page 1 rows, packed under the masthead to the template's bottom limit.
    const rowsTop = totalRows > 0 ? rows[0].getBoundingClientRect().top - rootTop : 0;
    // Page 1 of a split: its pinned footer blocks move to the final page.
    const page1Capacity = Math.max(200, measurePage(root, { skipAbsBlocks: true }).limit - rowsTop);
    let p1Height = 0;
    let p1End = 0;
    while (p1End < totalRows && p1Height + rowHeights[p1End] <= page1Capacity) {
      p1Height += rowHeights[p1End];
      p1End++;
    }
    // Enforce orphan rule: if only 1 row left for Page 2+, pull one back unless Page 1 needs it
    if (p1End === totalRows - 1 && p1End > 2) {
      p1End--;
    }
    // Enforce widow rule: min 2 rows on Page 1 if any rows exist
    if (p1End < 2 && totalRows >= 2) {
      p1End = Math.min(2, totalRows);
    }
    p1End = backOffKept(0, p1End);
    pages.push({ start: 0, end: p1End, blocks: [] });
    let currentRow = p1End;

    // Pages 2+, each packed to the full continuation capacity.
    while (currentRow < totalRows) {
      const contIdx = continuedHeaderFor(currentRow);
      const capacity = continuationCapacity - (contIdx >= 0 ? rowHeights[contIdx] : 0);
      let pHeight = 0;
      let pEnd = currentRow;

      while (pEnd < totalRows && pHeight + rowHeights[pEnd] <= capacity) {
        pHeight += rowHeights[pEnd];
        pEnd++;
      }

      if (pEnd === currentRow) {
        // At least one row per page (a single row taller than the page).
        pEnd = currentRow + 1;
      } else if (pEnd === totalRows - 1 && pEnd - currentRow > 1) {
        // Widow guard: the next page never carries a lone orphan row sitting by
        // itself above the totals block.
        pEnd--;
      }
      pEnd = backOffKept(currentRow, pEnd);

      pages.push({ start: currentRow, end: pEnd, blocks: [] });
      currentRow = pEnd;
    }

    // ── Place the last-page blocks ──────────────────────────────
    /** How many units, from unit `from` on, fit on page pi after its rows. */
    const place = (pi: number, from: number) => {
      for (let k = units.length - from; k > 0; k--) {
        const page = { ...pages[pi], blocks: units.slice(from, from + k).flat() };
        if (fits(page, pi, from + k === units.length)) return k;
      }
      return 0;
    };

    let last = pages.length - 1; // the page holding the last rows
    let placed = place(last, 0);
    // Stuck: the totals can't follow the last rows (or, with no blocks, the
    // rows plus whatever trails the table overrun the page). Carry the last two
    // rows to a fresh page so the totals keep ≥ 2 rows above them, as long as
    // two stay behind; a page of 3 or fewer rows keeps them, and the blocks
    // start the next page on their own.
    const stuck = units.length > 0 ? placed === 0 : !fits(pages[last], last, true);
    const lastRows = pages[last].end - pages[last].start;
    if (stuck && lastRows >= 4) {
      const cut = backOffKept(pages[last].start, pages[last].end - 2);
      pages.push({ start: cut, end: pages[last].end, blocks: [] });
      pages[last] = { ...pages[last], end: cut };
      last++;
      placed = place(last, 0);
    }
    pages[last].blocks = units.slice(0, placed).flat();

    // Whatever didn't fit starts a page of blocks alone, as many per page as
    // fit (at least one: a block taller than a page is clipped, not lost).
    while (placed < units.length) {
      pages.push({ start: totalRows, end: totalRows, blocks: [] });
      const pi = pages.length - 1;
      const k = Math.max(1, place(pi, placed));
      pages[pi].blocks = units.slice(placed, placed + k).flat();
      placed += k;
    }

    const totalPages = pages.length;

    // Render each page into jsPDF
    const pdf = new jsPDF({ unit: 'px', format: [794, 1123], compress: true });

    for (let p = 0; p < totalPages; p++) {
      if (p > 0) {
        pdf.addPage([794, 1123]);
      }
      const pageNode = buildPage(
        pages[p], p, p === totalPages - 1,
        totalPages > 1 ? `Page ${p + 1} of ${totalPages}` : null,
      );
      offscreenContainer.appendChild(pageNode);
      const canvas = await html2canvas(pageNode, {
        scale,
        useCORS: true,
        backgroundColor: computedBg,
        width: 794,
        height: 1123,
        windowWidth: 794,
        windowHeight: 1123,
      });
      pdf.addImage(canvas.toDataURL('image/png'), 'PNG', 0, 0, 794, 1123);
      addPageLinks(pdf, pageNode);
    }

    const blob = pdf.output('blob');
    return new File([blob], filename, { type: 'application/pdf' });
  } finally {
    offscreenContainer.remove();
  }
}

/** The page colours and font a continuation page paints with: the template's
 *  inline style first, its computed style otherwise, white/black/Helvetica last. */
function getEffectiveBgAndColor(el: HTMLElement) {
  const node = el;
  const child = (node.firstElementChild || node) as HTMLElement;

  let bg = node.style.backgroundColor || node.style.background || child.style.backgroundColor || child.style.background;
  let color = node.style.color || child.style.color;
  let fontFamily = node.style.fontFamily || child.style.fontFamily;

  if (!bg || bg === 'rgba(0, 0, 0, 0)' || bg === 'transparent') {
    bg = getComputedStyle(node).backgroundColor;
    if (!bg || bg === 'rgba(0, 0, 0, 0)' || bg === 'transparent') {
      bg = getComputedStyle(child).backgroundColor;
    }
  }

  if (!color || color === 'rgba(0, 0, 0, 0)' || color === 'transparent') {
    color = getComputedStyle(node).color;
    if (!color || color === 'rgba(0, 0, 0, 0)' || color === 'transparent') {
      color = getComputedStyle(child).color;
    }
  }

  if (!fontFamily) {
    fontFamily = getComputedStyle(node).fontFamily || getComputedStyle(child).fontFamily;
  }

  const effectiveBg = (bg && bg !== 'rgba(0, 0, 0, 0)' && bg !== 'transparent') ? bg : '#FFFFFF';
  const effectiveColor = (color && color !== 'rgba(0, 0, 0, 0)' && color !== 'transparent') ? color : '#000000';

  return { bg: effectiveBg, color: effectiveColor, fontFamily: fontFamily || "'Helvetica Neue', Arial, sans-serif" };
}

/** Trigger a browser download of a File without sending it anywhere. Used by the
 *  explicit download controls (confirm card, invoice detail) and as shareInvoice's
 *  non-share fallback. */
export function downloadFile(file: File): void {
  const url = URL.createObjectURL(file);
  const a = document.createElement('a');
  a.href = url;
  a.download = file.name;
  a.click();
  URL.revokeObjectURL(url);
}

/** Native share sheet — the locked send mechanism (no Twilio).
 *  'cancelled' means the user dismissed the share sheet: a normal choice, not a
 *  failure and NOT a send — the caller leaves the invoice unsent. Only when NO
 *  attempt can open a sheet does it fall through to a download so the user still
 *  gets their file.
 *
 *  `url` (optional) is the public pay link (/pay/<token>). Some platforms refuse
 *  a payload with BOTH files and a url (Brave on iOS, notably) — and the old code
 *  only asked canShare about the file, so it entered the try, share() threw on the
 *  files+url combo, and every send silently degraded to a download. So we build an
 *  ordered list of payloads (PDF+link → link-only → PDF-only) and only attempt one
 *  navigator.canShare actually approves for that EXACT payload. The link matters
 *  more than the attachment for an invoice (the pay page shows the full document),
 *  so link-only is preferred over downloading when the combo is refused. */
export async function shareInvoice(file: File, clientName: string, noun = 'Invoice', url?: string): Promise<'shared' | 'downloaded' | 'cancelled'> {
  const text = `${noun} for ${clientName}`;
  const canShare = (data: ShareData) =>
    typeof navigator !== 'undefined' && !!navigator.canShare?.(data);

  // Best payload first. With a pay link: try PDF+link, then fall back to the link
  // alone (never a silent download while a link can still be shared). Without one
  // (e.g. a quote): PDF only, unchanged from before.
  const attempts: ShareData[] = url
    ? [
        { files: [file], title: file.name, text, url },
        { title: file.name, text, url },
      ]
    : [{ files: [file], title: file.name, text }];

  for (const data of attempts) {
    if (!canShare(data)) continue; // platform won't take this exact payload
    try {
      await navigator.share(data);
      return 'shared';
    } catch (err) {
      // User dismissed the sheet → a real cancel: don't retry, don't download.
      if (err instanceof DOMException && err.name === 'AbortError') return 'cancelled';
      // Any other error (e.g. canShare lied about the combo) → try the next,
      // simpler payload, then the download below. Logged by name so a blocked
      // share (NotAllowedError) is traceable instead of silent.
      console.error('share attempt failed', err instanceof Error ? err.name : String(err), err);
    }
  }

  downloadFile(file);
  return 'downloaded';
}
