import type { Metadata, Viewport } from 'next';
import { Montserrat, Inter } from 'next/font/google';
import localFont from 'next/font/local';
import Splash from '@/components/Splash';
import './globals.css';

// Warm Premium dual-font strategy (Design Standard §3):
// Montserrat 700/800 — headlines, financial figures, wordmark.
// Inter 400/600 — body, labels, data. Nothing else.
const montserrat = Montserrat({ subsets: ['latin'], weight: ['700', '800'], variable: '--font-montserrat' });
const inter = Inter({ subsets: ['latin'], weight: ['400', '600'], variable: '--font-inter' });
// Material Symbols Outlined — the app's only icon system (§4). Self-hosted
// SUBSET generated by `npm run icons:build` from src/components/icon-names.ts
// (~9 KB vs the ~4 MB full font from the render-blocking Google Fonts
// stylesheet it replaces). next/font preloads it and serves it hashed/immutable.
// display 'block': icons stay invisible for the (browser-fixed, ~3s) block
// period instead of flashing their ligature text ("mic") in a fallback font;
// preloaded at ~9 KB it normally lands before first paint.
const symbols = localFont({
  src: '../fonts/material-symbols-outlined.woff2',
  variable: '--font-symbols',
  display: 'block',
  weight: '400',
  style: 'normal',
  // An icon font has no metric-compatible fallback — don't synthesize one.
  adjustFontFallback: false,
});

export const metadata: Metadata = {
  title: 'On It — Invoices done by talking',
  description: 'Speak your job. Get a branded invoice. Get paid.',
  manifest: '/manifest.json',
  icons: {
    icon: [
      { url: '/icons/favicon.ico', sizes: '16x16 32x32 48x48' },
      { url: '/icons/icon-32.png', sizes: '32x32', type: 'image/png' },
    ],
    apple: '/icons/apple-icon-180.png',
  },
};
export const viewport: Viewport = {
  themeColor: '#d4af37',
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  // Android keyboards default to `resizes-visual`: the soft keyboard overlays
  // the page and the layout viewport (and thus `h-dvh`) stays full-height, so
  // the in-flow chat input row ends up hidden behind the keyboard. `resizes-
  // content` makes the keyboard shrink the layout viewport instead, so `h-dvh`
  // collapses to the space above it — the input row lifts up and the messages
  // list stays scrollable. iOS already lifts it via its own visual-viewport
  // behavior, so this is Android-focused and safe there.
  interactiveWidget: 'resizes-content',
  // Light-only app. Stops iOS/Android dark mode from giving the canvas a dark
  // default before (or instead of) our cream background.
  colorScheme: 'light',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    // Inline cream background + color-scheme: painted from the HTML itself, so
    // no frame depends on the stylesheet having arrived. Never black, never
    // white. Mirrored in globals.css.
    <html
      lang="en"
      className={`${montserrat.variable} ${inter.variable} ${symbols.variable}`}
      style={{ backgroundColor: '#fff8f0', colorScheme: 'light' }}
    >
      <head>
        {/* Chrome fires `beforeinstallprompt` very early — often before React
            hydrates and the /install hook can attach its listener. This head
            script runs during parse, captures the event, prevents the mini-
            infobar, and stashes it on window so useInstallPrompt can adopt it on
            mount (its own listener still handles a late/second fire). Inline is
            allowed by the CSP's script-src 'unsafe-inline'. */}
        <script
          dangerouslySetInnerHTML={{
            __html:
              "window.__deferredInstallPrompt=null;" +
              "window.addEventListener('beforeinstallprompt',function(e){e.preventDefault();window.__deferredInstallPrompt=e;});" +
              "window.addEventListener('appinstalled',function(){window.__deferredInstallPrompt=null;});",
          }}
        />
      </head>
      <body>
        <Splash />
        {children}
      </body>
    </html>
  );
}
